RuntimeError: asyncio.run() cannot be called from a running event loop (#243)
chore: add cspell words
docs: Add few TODOs to install tools for troubleshooting
docs: Add Gource instructions for video generation
feat(devcontainer): Simplify post-create commands and install tools
feat(partcad): Improve project loading and config handling
feat(partcad): make render function asynchronous
feat(vscode): improve settings and docs

- Add instructions on how to generate a video using Gource.  Includes installation and command steps.
- Added missing details to clarify the command for generating the respective video.
- Also fixes a typo in a help message.
- Also, updated VS Code settings to deal with spelling problems.
- Refactor project loading logic to use a more descriptive variable name (`sub_folders`) improving code readability.
- Refined the VS Code settings (`settings.json`) by removing unused line, and configuring spell checking.
- Simplify post-create commands by combining update and install steps for utilities.
- This improves consistency and readability.
- Updated the `development.md` documentation to enhance the Gource installation and visualization instructions.