fix(ci): exclude failing Python 3.12 builds
This commit excludes failing Python 3.12 builds for macOS and Ubuntu.

- Excludes Python 3.12 on macOS due to `AttributeError: 'NoneType' object has no attribute 'TShape'`.
- Excludes Python 3.12 on Ubuntu due to `ModuleNotFoundError: No module named 'OCP.OCP'`.